// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: auth.proto

package authpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthGrpc_GoogleLogin_FullMethodName = "/auth.AuthGrpc/GoogleLogin"
)

// AuthGrpcClient is the client API for AuthGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthGrpcClient interface {
	GoogleLogin(ctx context.Context, in *GoogleLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthGrpcClient(cc grpc.ClientConnInterface) AuthGrpcClient {
	return &authGrpcClient{cc}
}

func (c *authGrpcClient) GoogleLogin(ctx context.Context, in *GoogleLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthGrpc_GoogleLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthGrpcServer is the server API for AuthGrpc service.
// All implementations must embed UnimplementedAuthGrpcServer
// for forward compatibility.
type AuthGrpcServer interface {
	GoogleLogin(context.Context, *GoogleLoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedAuthGrpcServer()
}

// UnimplementedAuthGrpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthGrpcServer struct{}

func (UnimplementedAuthGrpcServer) GoogleLogin(context.Context, *GoogleLoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GoogleLogin not implemented")
}
func (UnimplementedAuthGrpcServer) mustEmbedUnimplementedAuthGrpcServer() {}
func (UnimplementedAuthGrpcServer) testEmbeddedByValue()                  {}

// UnsafeAuthGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthGrpcServer will
// result in compilation errors.
type UnsafeAuthGrpcServer interface {
	mustEmbedUnimplementedAuthGrpcServer()
}

func RegisterAuthGrpcServer(s grpc.ServiceRegistrar, srv AuthGrpcServer) {
	// If the following call panics, it indicates UnimplementedAuthGrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthGrpc_ServiceDesc, srv)
}

func _AuthGrpc_GoogleLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGrpcServer).GoogleLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthGrpc_GoogleLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGrpcServer).GoogleLogin(ctx, req.(*GoogleLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthGrpc_ServiceDesc is the grpc.ServiceDesc for AuthGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthGrpc",
	HandlerType: (*AuthGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GoogleLogin",
			Handler:    _AuthGrpc_GoogleLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
